baseURL = 'http://amanihas.github.io/'
title        = "amanihas"
languageCode = "en-us"
theme = "hugo-theme-red-rose"


[params]
amani = "/img/author-pic.jpg"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
